# Generated by Django 6.0.3 on 2026-03-16 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokerages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descricao')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brokerages.brokerage', verbose_name='Corretora')),
            ],
            options={
                'verbose_name': 'Ramo',
                'verbose_name_plural': 'Ramos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descricao')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brokerages.brokerage', verbose_name='Corretora')),
                ('insurance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='coverages.insurancetype', verbose_name='Ramo')),
            ],
            options={
                'verbose_name': 'Cobertura',
                'verbose_name_plural': 'Coberturas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CoverageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descricao')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brokerages.brokerage', verbose_name='Corretora')),
                ('coverage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='coverages.coverage', verbose_name='Cobertura')),
            ],
            options={
                'verbose_name': 'Item de Cobertura',
                'verbose_name_plural': 'Itens de Cobertura',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('brokerage', 'coverage', 'name'), name='unique_coverage_item_per_brokerage')],
            },
        ),
        migrations.AddConstraint(
            model_name='insurancetype',
            constraint=models.UniqueConstraint(fields=('brokerage', 'slug'), name='unique_insurance_type_slug_per_brokerage'),
        ),
        migrations.AddConstraint(
            model_name='coverage',
            constraint=models.UniqueConstraint(fields=('brokerage', 'insurance_type', 'name'), name='unique_coverage_per_brokerage'),
        ),
    ]
