# Generated by Django 6.0.3 on 2026-03-16 00:47

import django.db.models.deletion
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokerages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('cnpj', models.CharField(max_length=18, validators=[utils.validators.validate_cnpj], verbose_name='CNPJ')),
                ('susep_code', models.CharField(blank=True, max_length=20, verbose_name='Codigo SUSEP')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('website', models.URLField(blank=True, verbose_name='Site')),
                ('contact_name', models.CharField(blank=True, max_length=150, verbose_name='Contato Principal')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email do Contato')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone do Contato')),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Logradouro')),
                ('number', models.CharField(blank=True, max_length=10, verbose_name='Numero')),
                ('complement', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, verbose_name='UF')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='insurers/', verbose_name='Logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('notes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brokerages.brokerage', verbose_name='Corretora')),
            ],
            options={
                'verbose_name': 'Seguradora',
                'verbose_name_plural': 'Seguradoras',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InsurerBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Ramo')),
                ('susep_branch_code', models.CharField(blank=True, max_length=20, verbose_name='Codigo do Ramo SUSEP')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brokerages.brokerage', verbose_name='Corretora')),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='insurers.insurer', verbose_name='Seguradora')),
            ],
            options={
                'verbose_name': 'Ramo',
                'verbose_name_plural': 'Ramos',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='insurer',
            constraint=models.UniqueConstraint(fields=('brokerage', 'cnpj'), name='unique_insurer_cnpj_per_brokerage'),
        ),
        migrations.AddConstraint(
            model_name='insurerbranch',
            constraint=models.UniqueConstraint(fields=('brokerage', 'insurer', 'name'), name='unique_branch_per_brokerage'),
        ),
    ]
