# Generated by Django 6.0.3 on 2026-03-16 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokerages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_free', models.BooleanField(default=False, verbose_name='Plano gratuito')),
                ('monthly_price_per_user', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço mensal por usuário')),
                ('yearly_price_per_user', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço anual por usuário')),
                ('trial_days', models.PositiveIntegerField(default=0, verbose_name='Dias de trial')),
                ('max_users', models.PositiveIntegerField(blank=True, null=True, verbose_name='Máximo de usuários')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('highlight_label', models.CharField(blank=True, max_length=50, verbose_name='Destaque')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('modules', models.ManyToManyField(blank=True, related_name='plans', to='brokerages.systemmodule', verbose_name='Módulos incluídos')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['sort_order', 'monthly_price_per_user', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Ativa'), ('pending_payment', 'Pagamento pendente'), ('overdue', 'Em atraso'), ('cancelled', 'Cancelada'), ('inactive', 'Inativa')], default='active', max_length=20, verbose_name='Status')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Mensal'), ('yearly', 'Anual')], default='monthly', max_length=20, verbose_name='Ciclo')),
                ('price_per_user', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço por usuário')),
                ('active_user_count', models.PositiveIntegerField(default=1, verbose_name='Usuários ativos')),
                ('started_at', models.DateField(verbose_name='Início')),
                ('trial_ends_at', models.DateField(blank=True, null=True, verbose_name='Fim do trial')),
                ('next_billing_at', models.DateField(blank=True, null=True, verbose_name='Próxima cobrança')),
                ('cancelled_at', models.DateField(blank=True, null=True, verbose_name='Cancelada em')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='brokerages.brokerage', verbose_name='Corretora')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan', verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('failed', 'Falhou'), ('refunded', 'Reembolsado'), ('overdue', 'Em atraso')], default='pending', max_length=20, verbose_name='Status')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('payment_method', models.CharField(choices=[('credit_card', 'Cartão de crédito'), ('pix', 'PIX'), ('bank_slip', 'Boleto'), ('manual', 'Manual')], default='manual', max_length=20, verbose_name='Forma de pagamento')),
                ('reference_code', models.CharField(blank=True, max_length=100, verbose_name='Referência')),
                ('due_date', models.DateField(verbose_name='Vencimento')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.subscription', verbose_name='Assinatura')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-due_date', '-created_at'],
            },
        ),
    ]
