# Generated by Django 6.0.3 on 2026-03-16 00:47

import django.db.models.deletion
import utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brokerage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legal_name', models.CharField(max_length=255, verbose_name='Razão social')),
                ('trade_name', models.CharField(blank=True, max_length=255, verbose_name='Nome fantasia')),
                ('cnpj', models.CharField(max_length=18, unique=True, validators=[utils.validators.validate_cnpj], verbose_name='CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Logradouro')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, verbose_name='UF')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('inactive', 'Inativa'), ('overdue', 'Pagamento em atraso')], default='active', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Corretora',
                'verbose_name_plural': 'Corretoras',
                'ordering': ['legal_name'],
            },
        ),
        migrations.CreateModel(
            name='SystemModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Módulo do sistema',
                'verbose_name_plural': 'Módulos do sistema',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BrokerageModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='brokerages.brokerage', verbose_name='Corretora')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_brokerage_modules', to=settings.AUTH_USER_MODEL, verbose_name='Liberado por')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brokerage_links', to='brokerages.systemmodule', verbose_name='Módulo')),
            ],
            options={
                'verbose_name': 'Módulo liberado para corretora',
                'verbose_name_plural': 'Módulos liberados para corretoras',
                'constraints': [models.UniqueConstraint(fields=('brokerage', 'module'), name='unique_brokerage_module')],
            },
        ),
    ]
