# Generated by Django 6.0.3 on 2026-03-16 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokerages', '0001_initial'),
        ('policies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endorsement_number', models.CharField(max_length=50, verbose_name='Numero do Endosso')),
                ('endorsement_type', models.CharField(choices=[('inclusion', 'Inclusao'), ('exclusion', 'Exclusao'), ('modification', 'Alteracao'), ('cancellation', 'Cancelamento'), ('transfer', 'Transferencia')], max_length=20, verbose_name='Tipo de Endosso')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('requested', 'Solicitado'), ('under_analysis', 'Em Analise'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('applied', 'Aplicado')], default='draft', max_length=20, verbose_name='Status')),
                ('request_date', models.DateField(verbose_name='Data da Solicitacao')),
                ('effective_date', models.DateField(verbose_name='Data de Efeito')),
                ('description', models.TextField(verbose_name='Descricao das Alteracoes')),
                ('premium_difference', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Diferenca de Premio')),
                ('notes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brokerages.brokerage', verbose_name='Corretora')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='endorsements', to='policies.policy', verbose_name='Apolice')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='endorsements', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
            ],
            options={
                'verbose_name': 'Endosso',
                'verbose_name_plural': 'Endossos',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='EndorsementDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('file', models.FileField(upload_to='endorsements/documents/', verbose_name='Arquivo')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brokerages.brokerage', verbose_name='Corretora')),
                ('endorsement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='endorsements.endorsement', verbose_name='Endosso')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_endorsement_documents', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Documento do Endosso',
                'verbose_name_plural': 'Documentos do Endosso',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='endorsement',
            constraint=models.UniqueConstraint(fields=('brokerage', 'endorsement_number'), name='unique_endorsement_number_per_brokerage'),
        ),
    ]
