# Generated by Django 6.0.3 on 2026-03-16 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokerages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Titulo')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brokerages.brokerage', verbose_name='Corretora')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Sessao de Chat',
                'verbose_name_plural': 'Sessoes de Chat',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Assistente')], max_length=10, verbose_name='Papel')),
                ('content', models.TextField(verbose_name='Conteudo')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brokerages.brokerage', verbose_name='Corretora')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_agent.chatsession', verbose_name='Sessao')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(verbose_name='Conteudo')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Gerado em')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dashboard_insights', to='brokerages.brokerage', verbose_name='Corretora')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_insights', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Insight do Dashboard',
                'verbose_name_plural': 'Insights do Dashboard',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='EntitySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('client', 'Cliente'), ('deal', 'Negociacao'), ('policy', 'Apolice'), ('proposal', 'Proposta'), ('claim', 'Sinistro')], max_length=20, verbose_name='Tipo')),
                ('entity_id', models.PositiveIntegerField(verbose_name='ID da Entidade')),
                ('content', models.TextField(verbose_name='Conteudo')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Gerado em')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entity_summaries', to='brokerages.brokerage', verbose_name='Corretora')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_summaries', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Resumo de Entidade',
                'verbose_name_plural': 'Resumos de Entidades',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='ai_agent_en_entity__fb9516_idx')],
            },
        ),
    ]
